name: shopping_app_example
description: "A Flutter shopping app example project using flutter_bloc and rxdart."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  dio: ^5.7.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  bloc_concurrency: ^0.2.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  
  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: true